=pod

=encoding utf8

Доброго всем

¡ ¡ ¡ ALL GLORY TO GLORIA ! ! !

=head1 О проекте

Это внутренний корпоративный портал учета для группы строительных контор.

Базовая браузерная нагрузка на фреймворк AngularJS (version >1.6)

Серверный Perl фреймворк - Mojolicious (version >7.*)

=head1 Основные модули системы

=head2 Управление списками сотрудников, групп, ролей и маршрутов системы

Это мощный модуль типа ActiveDirectory. Доступ в системе, различные привязки сотрудников к объектам строительства, должностям, бригадам, ...

  lib/Controll/Access.pm
  lib/Model/Access.pm
  static/js/components/access

=head2 Учет денежных средств

  lib/Controll/Waltex.pm

=head3 Движение денежных средств

Форма ввода прихода/расхода по контрагентам, сотрудникам, а также внутренние перемещения между проектами.

  lib/Controll/Waltex/Money.pm
  static/js/components/waltex/money


=head3 Отчет по денежным средствам

На основе данных движения ДС.

  lib/Controll/Waltex/Report.pm
  static/js/components/waltex/report

=head2 Учет рабочего времени

  lib/Controll/TimeWork.pm
  lib/Model/TimeWork.pm

=head3 Табель учета рабочего времени 

Форма одного месяца, одного объекта.

  static/js/components/timework/form.*

=head3 Сводка по табелю рабочего времени 

Начисление заработанных сумм, контроль баланса начислений и выплат.

  static/js/components/timework/report.*

=head2 Учет ТМЦ

  lib/Controll/TMC.pm
  lib/Model/TMC.pm

=head3 Заявки ТМЦ на объектах

Форма одной позиции заявки вводят на объектах. Список заявок.

  static/js/components/tmc/ask-form.*
  static/js/components/tmc/ask-table.*

=head3 Заявки ТМЦ на оплате

Форма ввода для снабженца к заявкам ТМЦ данных о факте оплаты.

  static/js/components/tmc/ask-snab-form.*
  static/js/components/tmc/ask-snab-table.*

=head1 SEE ALSO


=head1 AUTHOR

Михаил Че (Mikhail Che), C<< <mche[-at-]cpan.org> >>

=head1 BUGS / CONTRIBUTING

Please report any bugs or feature requests at L<https://github.com/mche/sost/issues>. Pull requests also welcome.

=head1 COPYRIGHT

Copyright 2017 Mikhail Che.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
